### ISSUE TITLE
traders wont stock batteries

### ISSUE THREAD

**Issue by snrfl** [ahuyn/anomaly-exo#9]
i can only find batteries from killing stalkers wearing exos. ive max rep with loners but neither trader will sell batteries no matter how long i wait. using debug to trade with multiple traders while refreshing inventories doesnt work either. i decided to poke my nose into the trader_autoinject script to see if there was something obviously wrong and when i look there is a note about monkey patching the update function and rattles off a quick example but i am dumb and dont know wtf it wants me to do, or if i should even be doing anything.

uh tl;dr traders dont sell any of the new items but everything else works

**Comment by aorushome** [comment]
Probably because of the false callback?

![axr_main callback_set] callback trader_on_restock doesn't exist!
~ ------------------------------------------------------------------------
~ STACK TRACEBACK:
 
	... axr_main.script (line: 258) in function 'callback_set'
	... _g.script (line: 105) in function 'RSC'
	... dxml_core.script (line: 201) in function 'RegisterScriptCallback'
	... exo_loot.script (line: 159) in function 'on_game_start'
	... axr_main.script (line: 324) in function 'on_game_start'
	... _g.script (line: 83) in function <... _g.script:74>
~ ------------------------------------------------------------------------

**Comment by snrfl** [comment]
oh i see. would there be a way to create a real callback or something? i would like to actually buy these items from traders because this mod is cool

**Comment by aorushome** [comment]
Hey, sorry for late reply. Simply change the script name from "exo_loot.script" to "z_exo_loot.script".
I tested it and it works, provided you have the reputation. Just go into debug mode, aim at a trader and refresh his inventory via F7 and select the refresh option.

**Im not 100% sure why**, but I guess the callback "trader_on_restock" from the "exo_loot.script" doesnt know what to do, since the callback gets created in the "trader_autoinject.script", which loads waay after the exo script. So the callback has nothing to work with. We solve the issue by renaming the "exo_loot.script", so that it loads after the callback from the "trader_autoinject.script" has been created. Dont know if you get it, but that is my assumption.

**Comment by snrfl** [comment]
thanks so much, traders are now stocking the new items. also thanks for explaining what u think was even going on with the scripts, i think you explained it very well. now me can enjoy mod in full : )
